[build-system]
# requires = ["setuptools", "wheel"]
# build-backend = "setuptools.build_meta"
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "kithara"
description = "LLM post-training library"
dynamic = ["version"]
license = {file = 'LICENSE'}
authors = [{name = 'Kithara Authors'}]
requires-python = ">= 3.11"
dependencies = [
        "flax>=0.7.0",
        "datasets",
        "huggingface-hub",
        "jax>=0.4.30",
        "jaxlib>=0.4.30",
        "keras>=3.8.0",
        "transformers>=4.45.1",
        "keras-nlp>=0.18.1",
        "google-api-python-client",
        "google-auth-httplib2",
        "google-auth-oauthlib",
        "ray[default]",
        "torch",
        "peft",
        "hf_transfer",
        "tabulate",
        # MaxText dependencies
        "aqtp",
        "grain-nightly",
        "orbax-checkpoint>=0.10.3",
        "google-cloud-logging",
        "tensorboardx",
        "ml-collections",
        "tensorflow_datasets",
        "sentencepiece",
        "tiktoken",
        "pathwaysutils@git+https://github.com/google/pathways-utils.git",
        "cloud-accelerator-diagnostics",
        "cloud-tpu-diagnostics",
        "ml-goodput-measurement"
]

[project.optional-dependencies]
dev = ["twine", "build"]

# [tool.setuptools.packages.find]
# where = ["kithara"]

# [tool.setuptools]
# package-dir = {"" = "."}
# packages = ["kithara"]

[tool.flit.module]
name = "kithara"


[project.urls]
Homepage = 'https://github.com/wenxindongwork/keras-tuner-alpha'
Repository = 'https://github.com/wenxindongwork/keras-tuner-alpha'
# Documentation = "https://readthedocs.org" 

# [tool.setuptools.dynamic]
# version = {attr = "kithara.__version__"}  # any module attribute compatible with ast.literal_eval
